### ISSUE TITLE
Introduce validation for the fields

### ISSUE THREAD

**Issue by ira-halenok** [AutomatedProcessImprovement/prosimos-frontend#25]
**Requirements**
Scenario Specification
Processes num: greater than one (> 1), integer
Start date-time: no limits

Resource profiles
cost per hour: decimals, greater than or equal 0

Resource allocation
Mean: always positive, 0 is allowed, decimals 
Std deviation: always positive, 0 is allowed, decimals
Distr func: a limited number of functions
_[discovery part simulate with negative std deviation]_

Branching:
- check three branches

**Tasks**
- [x] 'Scenario Specification' page
- [x] 'Resource profiles' page
- [x] 'Resource Allocation' page
- [x] 'Branching Gateways' page
